// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "76PdPcBXGDffPDBzjsqI21WIq36ZpsTvikuH9nLQqmLPbtju8jqddofyMLkVDUPphnnRuy";
}
}
}

